import { Inter } from "next/font/google";
import "./globals.css";

const inter=Inter({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <nave className='flex justify-between items-center'>
      <a href="/">Logo</a>
        <ul className=" flex space-x-4">
          <li>
            <a href="/contact">Contact</a>
          </li>
          <li>
            <a href="/about">about</a>
          </li>
        </ul>
      </nave>
        {children}
      </body>
    </html>
  );
}
